module Settings
  SCREEN_WIDTH = 640
  SCREEN_HEIGHT = 480
  BRICK_WIDTH = 80
  BRICK_HEIGHT = 16
  BRICKS_PER_ROW = 640 / 80
  PADDLE_MOVE = 5
  PADDLE_WIDTH = 80
  PADDLE_HEIGHT = 16
  REGULAR_BALL_AREA = 16
  RB_CENTRE_ON_PADDLE = (PADDLE_WIDTH - REGULAR_BALL_AREA) / 2
end
